<?php

namespace Database\Factories;

use App\Models\Customer;
use App\Models\DomesticBooking;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<DomesticBooking>
 */
class DomesticBookingFactory extends Factory
{
    protected $model = DomesticBooking::class;

    public function definition(): array
    {
        $trip = fake()->dateTimeBetween('+15 days', '+60 days');

        return [
            // booking_number is auto-generated by model boot if empty,
            // but we set it explicitly to avoid LIKE-based race in parallel tests.
            'booking_number'      => 'DM-TEST-' . fake()->unique()->numerify('######'),
            'customer_id'         => Customer::factory(),
            'type'                => 'package',
            'destination_city'    => 'الغردقة',
            'booking_date'        => now()->toDateString(),
            'trip_date'           => $trip->format('Y-m-d'),
            'duration_days'       => 5,
            'duration_nights'     => 4,
            'adults_count'        => 2,
            'children_count'      => 0,
            'infants_count'       => 0,
            'accommodation_type'  => 'double',
            'rooms_count'         => 1,
            'accommodation_grade' => '5_stars',
            'meal_plan'           => 'ai',
            'transport_type'      => 'private_car',
            'selling_price'       => 10000.00,
            'total_cost'          => 0,
            'net_profit'          => 0,
            'status'              => 'pending',
            'workflow_stage'      => 'sales',
        ];
    }

    public function closed(): static
    {
        return $this->state(['status' => 'completed', 'workflow_stage' => 'closed']);
    }

    public function cancelled(): static
    {
        return $this->state([
            'status'       => 'cancelled',
            'cancelled_at' => now(),
        ]);
    }

    public function withSellingPrice(float $price): static
    {
        return $this->state(['selling_price' => $price]);
    }

    public function inCity(string $city): static
    {
        return $this->state(['destination_city' => $city]);
    }

    public function ofType(string $type): static
    {
        return $this->state(['type' => $type]);
    }
}
