<?php

namespace Database\Factories;

use App\Models\Customer;
use App\Models\ReligiousBooking;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<ReligiousBooking>
 */
class ReligiousBookingFactory extends Factory
{
    protected $model = ReligiousBooking::class;

    public function definition(): array
    {
        $trip = fake()->dateTimeBetween('+30 days', '+90 days');

        return [
            // booking_number is auto-generated by model boot if empty,
            // but we set it explicitly to avoid MySQL-specific SQL in tests.
            'booking_number'     => 'UM-TEST-' . fake()->unique()->numerify('######'),
            'customer_id'        => Customer::factory(),
            'type'               => 'umrah',
            'booking_date'       => now()->toDateString(),
            'trip_date'          => $trip->format('Y-m-d'),
            'duration_days'      => 14,
            'adults_count'       => 2,
            'children_count'     => 0,
            'infants_count'      => 0,
            'visa_type'          => 'standard',
            'accommodation_type' => 'quad',
            'meal_plan'          => 'hp',
            'transport_type'     => 'flight',
            'mutawif_grade'      => 'economy',
            'selling_price'      => 10000.00,
            'total_cost'         => 0,
            'net_profit'         => 0,
            'exchange_rate_sar'  => 8.0000,
            'status'             => 'pending',
            'workflow_stage'     => 'sales',
        ];
    }

    public function closed(): static
    {
        return $this->state(['status' => 'completed', 'workflow_stage' => 'closed']);
    }

    public function withSellingPrice(float $price): static
    {
        return $this->state(['selling_price' => $price]);
    }
}
